atriaapp/atriaapi/urls.py
from django.urls import path, include
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
#from rest_framework_swagger.views import get_swagger_view

from .views import *


#schema_view = get_swagger_view(title='Pastebin API')

app_name = "atriaapi"

# app_name will help us do a reverse look-up latter.
urlpatterns = [
    path('calendar/', include([
        path('<int:year>/', include([
            path('<int:month>/', event_month_view, name='event-month-view'),
            path('<int:month>/<int:day>/', event_day_view, name='event-day-view'),
        ])),
    ])),    
    path('events/', AtriaEventView.as_view()),
    path('calendars/', AtriaCalendarView.as_view()),
    path('programs/', AtriaProgramView.as_view()),
#    url(r'^$', schema_view),
]

atriaapp/atriaapp/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

from atriacalendar.urls import urlpatterns as atriacalendar_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    #url(r'^api-auth/', include('rest_framework.urls')),
    path('api/atria/', include('atriaapi.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('indy/', include('indy_community.urls')),
]

urlpatterns += i18n_patterns(
    path('', include('atriacalendar.urls')),
)

atriaapp/atriacalendar/urls.py
"""
URL configuration for Atria Calendar app.
"""

from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings

from .forms import *
from .views import *

USER_NAMESPACE = getattr(settings, "USER_NAMESPACE", 'neighbour')
ORG_NAMESPACE = getattr(settings, "ORG_NAMESPACE", 'organization')

# Publicly accessible URL patterns
urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', SignupView.as_view(), name='signup'),
    path('org_signup/', OrgSignupView.as_view(), name='org_signup'),
    path('dashboard/', dashboard_view, name='dashboard'),
    path('contact/', contact_view, name='contact'),
    path('event/<int:occ_id>/', view_event_view, name='view_event'),
    path('opportunity/<int:occ_id>/<int:opp_id>/', view_opportunity_view, name='view_opportunity'),
    path('search_event/', search_event_view, name='search_event'),
    path('search_opportunity/', search_opportunity_view, name='search_opportunity'),
    path('search_neighbour/', search_neighbour_view, name='search_neighbour'),
    path('view_neighbour/', view_neighbour_view, name='view_neighbour'),
    path('view_neighbour/<email>/', view_neighbour_id_view, name='view_neighbour_id'),
    path('search_organization/', search_organization_view, name='search_organization'),
    path('view_organization/', view_organization_view, name='view_organization'),
    path('view_organization/<int:id>/', view_organization_id_view, name='view_organization_id'),
    path('', auth_views.LoginView.as_view(), name='login'),
]

# URL patterns accessible to all authenticated users
calendarpatterns = [
    path('', dashboard_view, name='calendar_home'),
    path('calendar', include([
        path('<int:year>/', atria_year_view, name='swingtime-yearly-view'),
        path('<int:year>/', include([
            path('<int:month>/', atria_month_view,
                 name='swingtime-monthly-view'),
            path('<int:month>/<int:day>/', atria_day_view,
                 name='swingtime-daily-view'),
        ])),
    ])),
    path('event-list/', EventListView.as_view(), name='event_list'),
    path('event-detail/', include([
        path('<int:pk>/', EventUpdateView.as_view(), name='swingtime-event'),
        path('<int:event_pk>/<int:pk>/', atria_occurrence_view,
             name='swingtime-occurrence'),
    ])),
    path('create_manage/', CreateManageView.as_view(), name='create_manage'),
    path('event/', EventCreateView.as_view(), name='event'),
    path('event/<int:occ_id>/copy/', CopyOccurranceView.as_view(), name='copy_occurrance'),
    path('event/<int:occ_id>/opportunities/', manage_opportunity_view, name='opportunities'),
    path('event/<int:occ_id>/opportunity/', OpportunityCreateView.as_view(), name='opportunity'),
    path('settings/', settings_view, name='settings'),
]

# URL patterns specific to all logged-in users
loggedinuserpatterns = [
    path('connect/', make_connection, name='make_connection'),
]

# URL patterns specific to neighbours
neighbourpatterns = [
    path('', include([
        path('profile/', neighbour_profile_view, name='profile'),
        path('', include(calendarpatterns)),
        path('', include(loggedinuserpatterns)),
        ])),
]

# URL patterns accessible only to organization Admins
organizationpatterns = [
    path('', include([
        path('profile/', organization_profile_view, name='profile'),
        path('create-event/', add_atria_event, name='swingtime-add-event'),
        path('create-event/participants/', add_participants,
             name='add_participants'),
        path('', include(calendarpatterns)),
        path('', include(loggedinuserpatterns)),
        ])),
]

urlpatterns.append(path(USER_NAMESPACE+'/', include((neighbourpatterns, 'atriacalendar'), namespace=USER_NAMESPACE)))
urlpatterns.append(path(ORG_NAMESPACE+'/', include((organizationpatterns, 'atriacalendar'), namespace=ORG_NAMESPACE)))
urlpatterns.append(path('', include(calendarpatterns)))

atriaapp/atriacalendar/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import Group, PermissionsMixin
from django.contrib.auth.signals import user_logged_in, user_logged_out
from django.db import models
from django.utils import timezone
from django.conf import settings

from datetime import datetime, date, timedelta

from swingtime import models as swingtime_models


USER_ROLE = getattr(settings, "DEFAULT_USER_ROLE", 'Attendee')
ORG_ROLE = getattr(settings, "DEFAULT_ORG_ROLE", 'Admin')
USER_NAMESPACE = getattr(settings, "USER_NAMESPACE", 'neighbour') + ':'
ORG_NAMESPACE = getattr(settings, "ORG_NAMESPACE", 'organization') + ':'


USER_ROLES = (
    'Admin',
    'Volunteer',
    'Attendee',
)


def url_namespace(role):
    if role == ORG_ROLE:
        return ORG_NAMESPACE
    else:
        return USER_NAMESPACE


def init_user_session(sender, user, request, **kwargs):
    target = request.POST.get('next', '/neighbour/')
    if 'organization' in target:
        if user.has_role(ORG_ROLE):
            orgs = AtriaRelationship.objects.filter(user=user, status="Active", relation_type__is_org_relation=True).all()
            if 0 < len(orgs):
                request.session['ACTIVE_ORG'] = str(orgs[0].org.id)
                request.session['ACTIVE_ROLE'] = ORG_ROLE
            else:
                # TODO for now just set a dummy default - logged in user has no org-enabled role
                request.session['ACTIVE_ROLE'] = USER_ROLE
        else:
            # TODO for now just set a dummy default - logged in user with no role assigned
            request.session['ACTIVE_ROLE'] = USER_ROLE
    else:
        if user.has_role('Volunteer'):
            request.session['ACTIVE_ROLE'] = 'Volunteer'
        elif user.has_role(USER_ROLE):
            request.session['ACTIVE_ROLE'] = USER_ROLE
        else:
            # TODO for now just set a dummy default - logged in user with no role assigned
            request.session['ACTIVE_ROLE'] = USER_ROLE

    role = request.session['ACTIVE_ROLE']
    namespace = url_namespace(role)
    request.session['URL_NAMESPACE'] = namespace


def clear_user_session(sender, user, request, **kwargs):
    if 'ACTIVE_ROLE' in request.session:
        del request.session['ACTIVE_ROLE']
    if 'ACTIVE_ORG' in request.session:
        del request.session['ACTIVE_ORG']
    request.session['URL_NAMESPACE'] = ''


user_logged_in.connect(init_user_session)

user_logged_out.connect(clear_user_session)


class UserManager(BaseUserManager):

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)

        user.set_password(password)
        user.save()

        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)

        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get('is_superuser') is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    Simple custom User class with email-based login.
    """
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=150, blank=True)
    is_staff = models.BooleanField(
        default=False,
        help_text="Designates whether the user can log into this admin site."
    )
    is_active = models.BooleanField(
        default=True,
        help_text=(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        )
    )
    date_joined = models.DateTimeField(default=timezone.now)
    last_login = models.DateTimeField(blank=True, null=True)
    phone_number = models.CharField(max_length=30, null=True, blank=True)

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'

    objects = UserManager()

    @property
    def roles(self):
        # -> Iterable
        # Produce a list of the given user's roles.

        return filter(self.has_role, USER_ROLES)

    def get_full_name(self):
        return "%s %s" % (self.first_name, self.last_name)

    def add_role(self, role):
        # String ->
        # Adds user to role group

        self.groups.add(Group.objects.get(name=role))

    def has_role(self, role):
        # String -> Boolean
        # Produce true if user is in the given role group.

        return self.groups.filter(name=role).exists()


# Code table for event programs - senior, youth, etc.
class AtriaEventProgram(models.Model):
    '''
    Simple ``Program`` classifcation.
    '''
    abbr = models.CharField(max_length=4, unique=True)
    label = models.CharField(max_length=50)

    def __str__(self):
        return self.label


# Base class for organizations that use the Atria platform
class AtriaOrganization(models.Model):
    org_name = models.CharField(max_length=40)
    date_joined = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=8)
    description = models.TextField(max_length=4000)
    location = models.CharField(max_length=80)
    tagline = models.CharField(max_length=80, blank=True)

    def __str__(self):
        return self.org_name + ", " + self.location

    def get_default_calendar(self):
        return self.atriacalendar_set.order_by('id')[0]


# collect events into a "calendar" that has a name and owner (can be an org or individual user)
class AtriaCalendar(models.Model):
    org_owner = models.ForeignKey(AtriaOrganization, on_delete=models.CASCADE, blank=True, null=True)
    user_owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    calendar_name = models.CharField(max_length=40, blank=True)

    def __str__(self):
        if self.org_owner:
            owner = str(self.org_owner)
        else:
            owner = str(self.user_owner)
        return owner + ':' + self.calendar_name


# Extend swingtime Event to add some custom fields
class AtriaEvent(swingtime_models.Event):
    calendar = models.ForeignKey(AtriaCalendar, on_delete=models.CASCADE, blank=True, null=True)
    program = models.CharField(max_length=32, blank=True)
    event_program = models.ForeignKey(
        AtriaEventProgram,
        verbose_name='event program',
        on_delete=models.CASCADE
    )
    location = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.title + ", " + self.location


class AtriaOccurrenceManager(swingtime_models.OccurrenceManager):

    def get_for_user(self, user):
        '''
        Returns a queryset of instances that belong to the given user's org.
        '''
        return self.filter(
            event__atriaevent__calendar__org_owner__atriarelationship__user=user)

    def get_for_org_id(self, org_id):
        '''
        Returns a queryset of instances that belong to the given user's org id.
        '''
        return self.filter(
            event__atriaevent__calendar__org_owner__id=org_id)

    def period_occurrences(self, start_dt=None, end_dt=None, event=None):
        '''
        Returns a queryset of for instances that have any overlap with a
        particular period.

        * ``*_dt`` may be either a datetime.datetime, datetime.date object, or
          ``None``. If ``None``, default to the current day.

        * ``event`` can be an ``Event`` instance for further filtering.
        '''
        start_dt = start_dt or datetime.now()
        start = datetime(start_dt.year, start_dt.month, start_dt.day)
        end_dt = end_dt or start
        end = end_dt.replace(hour=23, minute=59, second=59)
        qs = self.filter(
            models.Q(
                start_time__gte=start,
                start_time__lte=end,
            ) |
            models.Q(
                end_time__gte=start,
                end_time__lte=end,
            ) |
            models.Q(
                start_time__lt=start,
                end_time__gt=end
            )
        )

        return qs.filter(event=event) if event else qs


class AtriaOccurrence(swingtime_models.Occurrence):
    published = models.BooleanField(default=False)
    publisher = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    objects = AtriaOccurrenceManager()

    @property
    def atriaevent(self):
        return self.event.atriaevent

    @property
    def status(self):
        if not self.published:
            return 'draft'

        days_until = self.days_until()

        if days_until < 0:
            return 'past'
        if days_until > 1:
            return '%s+ days' % days_until
        if days_until == 1:
            return '1+ day'

        return 'today'

    def days_until(self):
        return (self.start_time.date() - timezone.now().date()).days

    @property
    def volunteer_total(self):
        total = self.atriaeventattendance_set\
                .filter(attendance_type__attendance_type='Volunteer')\
                .aggregate(sum=models.Sum('user_count'))['sum']

        return total if total else 0

    @property
    def attendee_total(self):
        total = self.atriaeventattendance_set\
                .filter(attendance_type__attendance_type='Attendee')\
                .aggregate(sum=models.Sum('user_count'))['sum']

        return total if total else 0

atriaapp/atriacalendar/templates/atriacalendar/pagesForms/eventCopyForm.html
{% extends 'base_nav.html' %}

{% load i18n %}
{% load atria_custom_tags %}

{# Set local template variable: #}
{% get_settings_value LANGUAGES "LANGUAGES" %}

{% load static %}

{% block main_content %}
	<div class='inside-body'>

		<div class='center-body'>
			<div class='innercont-center-body'>
				<div class='innercont-center-inner'>
                <div class='accounts-events'>
					<div class='form-cont'>
						<h2>Event Occurrence</h2>
						<div class='newsfeed-post-seperator'></div>
	                    <div class='btns-cont'>
	                        <table class="accounts-events-table">
	                            <tr>
	                                <td>Title:</td><td>{{ atriaoccurrence.event.title }}</td>
	                            </tr>
	                            <tr>
	                                <td>Start Date/Time:</td><td>{{ atriaoccurrence.start_time|date:"Y-m-d g:i a" }}</td>
	                            </tr>
	                            <tr>
	                                <td>Publisher:</td><td>{{ atriaoccurrence.publisher }}</td>
	                            </tr>
	                            <tr>
	                                <td>Attendee Total:</td><td>{{ atriaoccurrence.attendee_total }}</td>
	                            </tr>
	                            <tr>
	                                <td>Volunteer Total:</td><td>{{ atriaoccurrence.volunteer_total }}</td>
	                            </tr>
	                            <tr>
	                                <td>Status:</td><td>{{ atriaoccurrence.status }}</td>
	                            </tr>
	                        </table>
	                    </div>
                    </div>
		            <form method='post' action=''>{% csrf_token %}
					<div class='form-cont'>
						<h2>Copy Event Form</h2>
						<div class='newsfeed-post-seperator'></div>
						{{ form.occ_id }}
                        <div class='form-date-time-cont'>
                            <div>
                                <h5>Date</h5>
                                <input type="date" id='event-form-date' name='day' required :value='localeDateString' @input='localeDateString = $event.target.valueAsDate'>
                            </div>
                            <div>
                                <h5>Time</h5>
                                <input type="time" id='event-form-time' name='start_time_delta' v-model='localeTimeString'>
                            </div>
                        </div>

                        {{ form.errors }}

                        <button type='submit' class='btn btn-create-post'>Post</button>
					</div>
					</form>
				</div>
			</div>
		</div>
	</div>

	<script>
		$(document).ready(function() {

			$('#event-form-title').keyup(function() {
				$('#form-view-title').text($(this).val());
			});

			$('#event-form-desc').keyup(function() {
				$('#form-view-desc').text($(this).val());
			});

			$('#event-form-time').keyup(function() {
				$('#form-view-time').text($(this).val());
			});

			$('#event-form-local').keyup(function() {
				$('#form-view-local').text($(this).val());
			});

		});
	</script>
{% endblock %}

atriaapp/atriacalendar/templates/atriacalendar/pagesForms/eventForm.html
{% extends 'base_nav.html' %} {% load i18n %} {% load atria_custom_tags %} {# Set local template variable: #} {% get_settings_value LANGUAGES "LANGUAGES" %} {% load static %} {% block main_content %}
<div class='inside-body'>
    <div class='center-body'>
        <div class='innercont-center-body'>
            <form method='post' action=''>{% csrf_token %}
                <div id='event-form' class='innercont-center-inner'>
                    <div class='form-cont'>
                        <h2>Event Form</h2>
                        <div class='newsfeed-post-seperator'></div>
                        {{ form.occ_id }}
                        <div>
                            <h5>Title</h5>
                            {{ form.title }}
                        </div>

                        <div>
                            <h5>Description</h5>
                            {{ form.description }}
                        </div>

                        <div class='form-date-time-cont'>
                            <div>
                                <h5>Date</h5>
                                <input type="date" id='event-form-date' name='day' required :value='localeDateString' @input='localeDateString = $event.target.valueAsDate'>
                            </div>
                            <div>
                                <h5>Time</h5>
                                <input type="time" id='event-form-time' name='start_time_delta' v-model='localeTimeString'>
                            </div>
                        </div>

                        <div>
                            <h5>Location</h5>
                            {{ form.location }}
                        </div>

                        <div>
                            <h5>Event Type</h5>
                            {{ form.event_type }}
                        </div>

                        <!-- <div>
									<h5>Calendar</h5>
									{{ form.calendar }}
								</div>

								<div>
									<h5>Program</h5>
									<input type="text" name="program" maxlength="32" id="id_program">
								</div> -->

                        <div>
                            <h5>Event Program</h5>
                            {{ form.event_program }}
                        </div>

                        <!-- <div class='add-opp-cont'>
									<div>
										<h5>Add Opportunities</h5>
										<input type="text" id='event-form-opp'>
									</div>
									<div class='btn btn-add-opp' id='btn-add-opp'>+ add</div>
								</div> -->
                        {{ form.errors }} {% verbatim %}

                        <button type='submit' class='btn btn-create-post'>Post</button>
                    </div>
                    <!-- <div class='form-view-cont'>
								<h2>Preview Event Post</h2>
								<div class='newsfeed-post-seperator'></div>
								<div class='form-view-top-cont'>
									<div class='form-view-img-info'>
										<div class='form-view-img'>
											{% endverbatim %}
												<img src="{% static "/atriacalendar/accounticon.png" %}">
											{% verbatim %}
										</div>

										<div class='form-view-info'>
											<div>
												<h2>Your Organization Name</h2>
											</div>
											<div>
												<h5>Your Organization tagline</h5>
											</div>
											<div>
												<h6>Today's Date</h6>
											</div>
										</div>
									</div>
								</div>

								<div>
									<h4 id='form-view-title'>{{ title || 'Event Title' }}</h4>
									<p id='form-view-desc'></p>
								</div>

								<div>
									<h4>Time / Date / Location</h4>
									<p id='form-view-time'>{{ localeTimeString12h }}</p>
									<p id='form-view-date'>{{ localeDateString }}</p>
									<p id='form-view-local'>{{ location }}</p>
								</div>

								<div>
									<h4>Event Opportunities:</h4>
									<ul>
										<li></li>
										<li></li>
										<li></li>
										<li></li>
										<li></li>
									</ul>
								</div>
								<br>
								<button type='submit' class='btn btn-create-post'>Post</button>
							</div> -->
                </div>
                {% endverbatim %}
        </div>
    </div>
</div>

<!-- development version, includes helpful console warnings -->
<!-- script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script -->
<!-- production version, optimized for size and speed -->
<script src="https://unpkg.com/vue"></script>
<script src="https://cdn.jsdelivr.net/npm/axios@0.12.0/dist/axios.min.js"></script>
<script src="{% static " /atriacalendar/vue_create_event.js " %}"></script>
{% endblock %}

atriaapp/atriacalendar/templates/atriacalendar/pagesForms/form_response.html
{% extends 'base_nav.html' %}

{% load i18n %}

{% block page_title %} {% trans "Form Response" %} {% endblock %}

{% block main_content %} 

  <div class='inside-body'>
    <div class='center-body'>
      <div class='innercont-center-body'>
        <div class='innercont-center-inner'>
          <div class='form-cont'>
            <h2>{{ msg }}</h2>
              <div>
                <h5>{{ msg_txt }}</h5>
              </div>
              <div>
                <h5>{{ msg_txt2 }}</h5>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

atriaapp/atriacalendar/templates/atriacalendar/pagesForms/makeConnection.html
{% extends 'base_nav.html' %}

{% load i18n %}
{% load atria_custom_tags %}
{% load session_namespaced_url %}

{# Set local template variable: #}
{% get_settings_value LANGUAGES "LANGUAGES" %}

{% load static %}

{% block main_content %}
  <div class='inside-body'>
    <div class='center-body'>
      <div class='innercont-center-body'>
        <div class='innercont-center-inner'>
          <div class='form-cont'>
            <h2>Make Connection Request</h2>
            <div class='newsfeed-post-seperator'></div>
            <form action="{% snurl 'make_connection' %}" method="POST">
              {% csrf_token %}
              {% for field in form %}
                <div>
                  <h5>{{ field.label_tag }}</h5>
                  {{ field }}
                  {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                  {% endfor %}
                </div>
              {% endfor %}
              <button class='btn' type="submit">Submit</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

atriaapp/atriacalendar/templates/atriacalendar/pagesForms/oppertunityForm.html
<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">

	<title></title>

	<meta name="author" content="">
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="viewport" content="width=device-width,initial-scale=1">

	<link rel="stylesheet" href="../css/style.css" type="text/css">
	<link rel="stylesheet" href="../css/navigations.css" type="text/css">
	<link rel="shortcut icon" href="">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,500,700" rel="stylesheet">

	<script src="https://code.jquery.com/jquery-1.10.2.js"></script>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
</head>

<body>

	<div id='navigation'>
	</div>

	<div class='inside-body'>

		<div class='center-body'>
			<div class='innercont-center-body'>
				<div class='innercont-center-inner'>
					<div class='form-cont'>
						<h2>Opportunity Form</h2>
						<div class='newsfeed-post-seperator'></div>
						<div>
							<h5>Title</h5>
							<input type="text" id='event-form-title'>
						</div>

						<div>
							<h5>Description</h5>
							<textarea rows="6" cols="37" id='event-form-desc'></textarea>
						</div>

						<div>
							<h5>Start Date</h5>
							<input type="date" id='event-form-date'>
						</div>
					</div>
					<div class='form-view-cont'>
						<h2>Preview Opportunity Post</h2>
						<div class='newsfeed-post-seperator'></div>
						<div class='form-view-top-cont'>
							<div class='form-view-img-info'>
								<div class='form-view-img'>
									<img src='../imgs/accounticon.png'>
								</div>

								<div class='form-view-info'>
									<div>
										<h2>Your Organization Name</h2>
									</div>
									<div>
										<h5>Your Organization tagline</h5>
									</div>
									<div>
										<h6>Todays Date</h6>
									</div>
								</div>
							</div>
						</div>

						<div>
							<h4 id='form-view-title'></h4>
							<p id='form-view-desc'></p>
						</div>

						<div>
							<h4>Start Date</h4>
							<p id='form-view-time'></p>
						</div>
						<br>
						<div class='btn btn-create-post'>Post</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<script>
		$(document).ready(function() {

			$("#navigation").load("../pageIncludes/navigation.html");

			$('#event-form-title').keyup(function() {
				$('#form-view-title').text($(this).val());
			});

			$('#event-form-desc').keyup(function() {
				$('#form-view-desc').text($(this).val());
			});

			$('#event-form-time').keyup(function() {
				$('#form-view-time').text($(this).val());
			});

			$('#event-form-local').keyup(function() {
				$('#form-view-local').text($(this).val());
			});

		});
	</script>
</body>

</html>